Final Figures
================================================================================
```{r data-collection}
setwd('~/Desktop/coursera-data-analysis/assignments/2/')
load('data/raw/samsungData.rda')

# literally hundreds of variables:
#names(samsungData)

unique(samsungData$subject)
# 1..30 --> minus: 2, 4, 9, 10, 12, 13, 18, 20, 24

### clean it up: ###
# `activity` as factor
samsungData$activity <- as.factor(samsungData$activity)

# clean the duplicate column names
for (n in 303:316) {
  colnames(samsungData)[n] <- paste("X-", colnames(samsungData)[n], sep="")
}
for (n in 317:330) {
  colnames(samsungData)[n] <- paste("Y-", colnames(samsungData)[n], sep="")
}
for (n in 331:344) {
  colnames(samsungData)[n] <- paste("Z-", colnames(samsungData)[n], sep="")
}
for (n in 382:395) {
  colnames(samsungData)[n] <- paste("X-", colnames(samsungData)[n], sep="")
}
for (n in 396:409) {
  colnames(samsungData)[n] <- paste("Y-", colnames(samsungData)[n], sep="")
}
for (n in 410:423) {
  colnames(samsungData)[n] <- paste("Z-", colnames(samsungData)[n], sep="")
}
for (n in 461:474) {
  colnames(samsungData)[n] <- paste("X-", colnames(samsungData)[n], sep="")
}
for (n in 475:488) {
  colnames(samsungData)[n] <- paste("Y-", colnames(samsungData)[n], sep="")
}
for (n in 489:502) {
  colnames(samsungData)[n] <- paste("Z-", colnames(samsungData)[n], sep="")
}

# short-cut to sanitized column names: (coerce out `-` and `(` and `)`)
samsungData <- data.frame(samsungData)

set.seed(20130228)

trainConstants = c(1, 3, 5, 6)
testConstants = c(27, 28, 29, 30)
remainderSubjects = setdiff(setdiff(unique(samsungData$subject), trainConstants), testConstants)
trainConstants <- c(trainConstants, setdiff(remainderSubjects,
                                            sample(remainderSubjects, length(remainderSubjects)/2)))
testConstants <- c(testConstants, setdiff(remainderSubjects, trainConstants))


trainData = samsungData[samsungData$subject %in% trainConstants,]
testData = samsungData[samsungData$subject %in% testConstants,]
```

```{r create-plots}
### PDF open:
pdf(file="samsung-data-analysis-2up.pdf", height=11, width=8.5)

par(mfrow=c(2,1))

trainData.for.tree <- trainData
clean.ugly.col.names <- c("fBodyAccJerk.maxInds.X", "fBodyAccJerk.std...X",
                          "tGravityAcc.min...X", "tGravityAcc.max...Y",
                          "tBodyAccMag.std..", "tGravityAcc.arCoeff...Y.2",
                          "tBodyGyro.arCoeff...Y.1")
alpha.order <- c("A", "B", "C", "D", "E", "F", "G")
for (n in 1:length(clean.ugly.col.names)) {
  colnames(trainData.for.tree)[which(names(trainData.for.tree) == clean.ugly.col.names[n])] <- alpha.order[n]
}

trainTree <- tree(activity ~ A + B + C + D + E + F + G, data=trainData.for.tree)
plot(trainTree, lwd=3)
title(main="Figure 1. Classification Tree for Samsung Data (Training)")
text(trainTree, col="red", bg="white", adj=c(0.5, 0.25)) #adj=c(1.1,-0.1)
legend("topright", legend=c("A = fBodyAccJerk-maxInds-X",
                      "B = fBodyAccJerk-std())-X",
                      "C = tGravityAcc-min()-X",
                      "D = tGravityAcc-max()-Y",
                      "E = tBodyAccMag-std()",
                      "F = tGravityAcc-arCoeff()-Y,2",
                      "G = tBodyGyro-arCoeff()-Y,1"),
       cex=0.75)

plot(jitter(trainData$fBodyAccJerk.maxInds.X), jitter(trainData$fBodyAccJerk.std...X),
     col=as.factor(trainData$activity), pch=19, cex=0.75,
     xlab="fBodyAccJerk-maxInds-X",
     ylab="fBodyAccJerk-std()-X",
     main="Figure 2. Activity Type by Linear Acceleration (Train)")
legend("topright",
       legend=levels(trainData$activity),
       col=1:6,
       pch=19)

# close PDF
dev.off()
```